# The default West manifest file to be used for Zephyr.

manifest:
  defaults:
    remote: upstream
    revision: master

  remotes:
    - name: upstream
      url-base: file:////projects/github
#      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      revision: d8285e4adff8589fc7def1965d7347a6e5cdc7a7

