# The default West manifest file to be used for Zephyr.

manifest:
  defaults:
    remote: zephyrproject-rtos
    revision: master

  remotes:
    - name: zephyrproject-rtos
      url: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
