# The default West manifest file to be used for Zephyr.

manifest:
  defaults:
    remote: upstream
    revision: master

  remotes:
    - name: upstream
      url: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
    - name: mcuboot
      path: zephyr/mcuboot
    - name: west
      path: zephyr/west
